# settings.yml
symbols:
  - 'SPY'
  - 'QQQ'
shortables:
  - 'SPY'
  - 'QQQ'
evaluable_strategies:  # Use attribute name in `class Strategies`, module `types.py`
  - sma       # Profitable SMA
  - rsi_sma   # Profitable RSI(14) SMA
  - rsi_rc    # Profitable RSI(14) RC
  - rsi_2b    # Profitable RSI(14) 2B